[versions]
changelog = "2.4.0"
detekt = "1.23.8"
intellij-platform = "2.9.0"
junit = "4.13.2"
kotlin = "2.2.20"
kotlinter = "5.2.0"
kover = "0.9.1"
qodana = "2025.2.1"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
